name: Deploy static site to Azure Web App - afriqueeuropeconnexionvmetcweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CF8131694CAB410B87815C4EC8A41EE1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4744DE4E80434FB0A6A2DC42065E6FD8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6258519989944BCEBD47D5ED24013E24 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'afriqueeuropeconnexionvmetcweb'
          package: .
